### PR TITLE
exclude tests when google creds file not found

### LINKED ISSUE #16: Dependabot can't access secrets and fails pull request tests
This error prevents any tests from Dependabot to pass (Dependabot can't access secrets)
I can try to fix this by splitting Dependabot workflows from the others (Will improve CI)
let me know if you want me to work on this

The error in Dependabot PR:
```
Error: google-github-actions/auth failed with: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.
```

### PR DESCRIPTION
**Pull request by ohad24**
closes #16 

@ofersadan85 What do you think ? on my machine no test is failing

And another questions, How this secret issue not affecting MONGO_URI ? or maybe it will..

### CODE REVIEW

**Comment by ofersadan85** [comment]
Looks great! Did you test to see what happens when the file/variable is missing?

If it runs as expected, I can split dependabot tests from normal tests in the worklows, so we can fix #16

**Comment by ofersadan85** [comment]
This is the log if google credentials is ok but MONGO_URI is missing:

```
tests/api/test_main.py::test_read_main PASSED                                                                                                                                        [  1%]
tests/api/test_main.py::TestCreateUser::test_accept_terms_of_service PASSED                                                                                                          [  3%]
tests/api/test_main.py::TestCreateUser::test_create_user PASSED                                                                                                                      [  5%]
tests/api/test_main.py::TestCreateUser::test_create_user_duplicate PASSED                                                                                                            [  7%]
tests/api/test_main.py::TestLogin::test_login PASSED                                                                                                                                 [  8%]
tests/api/test_main.py::TestLogin::test_login_failed PASSED                                                                                                                          [ 10%]
tests/api/test_main.py::TestUserAccess::test_get_current_user PASSED                                                                                                                 [ 12%]
tests/api/test_main.py::TestUserAccess::test_auth_inactive_user PASSED                                                                                                               [ 14%]
tests/api/test_main.py::TestUserAccess::test_superuser_access PASSED                                                                                                                 [ 15%]
tests/api/test_main.py::TestUserAccess::test_superuser_no_access PASSED                                                                                                              [ 17%]
tests/api/test_main.py::TestBrokenToken::test_access_invalid_token PASSED                                                                                                            [ 19%]
tests/api/test_main.py::TestBrokenToken::test_access_removed_user PASSED                                                                                                             [ 21%]
tests/api/test_main.py::TestUserUpdateData::test_update_user PASSED                                                                                                                  [ 22%]
tests/api/test_main.py::TestUserUpdateData::test_update_different_user PASSED                                                                                                        [ 24%]
tests/api/test_main.py::TestHelpers::test_KML_translate PASSED                                                                                                                       [ 26%]
tests/api/test_main.py::TestDetectImage::test_detect_image PASSED                                                                                                                    [ 28%]
tests/api/test_observations.py::TestObservation::test_create_observation PASSED                                                                                                      [ 29%]
tests/api/test_observations.py::TestObservation::test_observation_id PASSED                                                                                                          [ 31%]
tests/api/test_observations.py::TestObservation::test_upload_image[Minimum metadata + with gps data] PASSED                                                                          [ 33%]
tests/api/test_observations.py::TestObservation::test_upload_image[Maximum metadata + with gps data] PASSED                                                                          [ 35%]
tests/api/test_observations.py::TestObservation::test_upload_image[Minimum metadata + with no gps data] PASSED                                                                       [ 36%]
tests/api/test_observations.py::TestObservation::test_upload_image[Maximum metadata + with no gps data] PASSED                                                                       [ 38%]
tests/api/test_observations.py::TestObservation::test_image_metadata PASSED                                                                                                          [ 40%]
tests/api/test_observations.py::TestObservation::test_update_image_metadata FAILED                                                                                                   [ 42%]
tests/api/test_observations.py::TestObservation::test_delete_image PASSED                                                                                                            [ 43%]
tests/api/test_observations.py::TestObservation::test_add_comment PASSED                                                                                                             [ 45%]
tests/api/test_observations.py::TestObservation::test_get_comments PASSED                                                                                                            [ 47%]
tests/api/test_observations.py::TestObservation::test_submit_observation PASSED                                                                                                      [ 49%]
tests/api/test_observations.py::TestObservation::test_get_one_observation PASSED                                                                                                     [ 50%]
tests/api/test_observations.py::TestObservation::test_edit_header PASSED                                                                                                             [ 52%]
tests/api/test_observations.py::TestObservation::test_get_observations PASSED                                                                                                        [ 54%]
tests/api/test_observations.py::TestObservation::test_rotate_image PASSED                                                                                                            [ 56%]
tests/api/test_observations.py::TestObservation::test_images_limit PASSED                                                                                                            [ 57%]
tests/api/test_observations.py::TestObservation::test_get_observation_w_no_images PASSED                                                                                             [ 59%]
tests/api/test_observations.py::TestObservation::test_delete_observation PASSED                                                                                                      [ 61%]
tests/api/test_plant.py::TestPlant::test_get_plant[science_name0] SKIPPED (got empty parameter set ['science_name'], function test_get_plant at /home/ofer/encyclo-flower/tests/...) [ 63%]
tests/api/test_plant.py::TestPlant::test_get_plant_not_found PASSED                                                                                                                  [ 64%]
tests/api/test_plant.py::TestSearch::test_no_params PASSED                                                                                                                           [ 66%]
tests/api/test_plant.py::TestSearch::test_no_results PASSED                                                                                                                          [ 68%]
tests/api/test_plant.py::TestSearch::test_search FAILED                                                                                                                              [ 70%]
tests/api/test_plant.py::TestSearch::test_search_with_multi_params[params0-2] FAILED                                                                                                 [ 71%]
tests/api/test_plant.py::TestSearch::test_search_with_multi_params[params1-10] FAILED                                                                                                [ 73%]
tests/api/test_plant.py::TestSearch::test_search_with_multi_params[params2-13] FAILED                                                                                                [ 75%]
tests/api/test_plant.py::TestSearch::test_search_with_multi_params[params3-1] FAILED                                                                                                 [ 77%]
tests/api/test_plant.py::TestSearch::test_search_with_multi_page FAILED                                                                                                              [ 78%]
tests/api/test_plant.py::TestSearch::test_search_page_out_of_range FAILED                                                                                                            [ 80%]
tests/api/test_questions.py::TestQuestion::test_create_question PASSED                                                                                                               [ 82%]
tests/api/test_questions.py::TestQuestion::test_add_new_image_metadata PASSED                                                                                                        [ 84%]
tests/api/test_questions.py::TestQuestion::test_add_images PASSED                                                                                                                    [ 85%]
tests/api/test_questions.py::TestQuestion::test_add_comment SKIPPED (currently broken)                                                                                               [ 87%]
tests/api/test_questions.py::TestQuestion::test_get_question PASSED                                                                                                                  [ 89%]
tests/api/test_questions.py::TestQuestion::test_get_all_questions PASSED                                                                                                             [ 91%]
tests/api/test_questions.py::TestQuestion::test_rotate_image PASSED                                                                                                                  [ 92%]
tests/api/test_questions.py::TestQuestion::test_delete_image PASSED                                                                                                                  [ 94%]
tests/api/test_questions.py::TestQuestion::test_delete_image_as_editor PASSED                                                                                                        [ 96%]
tests/api/test_questions.py::TestQuestion::test_set_answer FAILED                                                                                                                    [ 98%]
tests/api/test_questions.py::TestQuestion::test_delete_question PASSED                                                                                                               [100%]
```

**Review by ofersadan85 — APPROVED** [review]
Looks great

**Comment by ohad24** [comment]
> Looks great! Did you test to see what happens when the file/variable is missing?
> 
> If it runs as expected, I can split dependabot tests from normal tests in the worklows, so we can fix #16

With this change why you need to split the dependabot tests, they can use the main one

**Comment by ofersadan85** [comment]
> > Looks great! Did you test to see what happens when the file/variable is missing?
> > 
> > If it runs as expected, I can split dependabot tests from normal tests in the worklows, so we can fix #16
> 
> With this change why you need to split the dependabot tests, they can use the main one

I still need to make sure it doesn't even TRY to access secrets, but normal test should

**Comment by ohad24** [comment]
> MONGO_URI

MONGO_URI is present, if not, all the tests will fail when DB connection string is not present.
Each API requests need to have access to DB

**Comment by ofersadan85** [comment]
> > > Looks great! Did you test to see what happens when the file/variable is missing?
> > > 
> > > If it runs as expected, I can split dependabot tests from normal tests in the worklows, so we can fix #16
> > 
> > With this change why you need to split the dependabot tests, they can use the main one
> 
> I still need to make sure it doesn't even TRY to access secrets, but normal test should

See here

**Comment by ohad24** [comment]
> > > > Looks great! Did you test to see what happens when the file/variable is missing?
> > > > If it runs as expected, I can split dependabot tests from normal tests in the worklows, so we can fix #16
> > > 
> > > 
> > > With this change why you need to split the dependabot tests, they can use the main one
> > 
> > 
> > I still need to make sure it doesn't even TRY to access secrets, but normal test should
> 
> [#16 (comment)](https://github.com/ohad24/encyclo-flower/issues/16#issuecomment-1063267137)

Thank you

**Pull request merged**
